#define CLASS 0
#define INHERITS 1
#define IF 2
#define THEN 3
#define ELSE 4
#define FI 5
#define WHILE 6
#define LOOP 7
#define POOL 8
#define LET 9
#define IN 10
#define CASE 11
#define OF 12
#define ESAC 13
#define NEW 14
#define TRUE 15
#define FALSE 16
#define ID 17
#define TYPE 18
#define INTEGER 19
#define STRING 20
#define SELF 21
#define SELF_TYPE 22
#define LEFT_PARENTHESIS 24
#define RIGHT_PARENTHESIS 25
#define SEMI_COLON 26
#define PLUS 27
#define MINUS 28
#define TIMES 29
#define OVER 30
#define ASSIGN 31
#define LESS_THAN 32
#define LESS_EQUAL 33
#define EQUAL 34
#define BRANCH 44
#define TILDE 35
#define NOT 36
#define ISVOID 37
#define SINGLE_COMMENT 38
#define MULTI_COMMENT 39
#define LEFT_BRACKETS 40
#define RIGHT_BRACKETS 41
#define COLON 42
#define DOT 43
#define COMMA 44
#define INVALID 45